server:
  port: 8080

spring:
  application:
    name: API-GATEWAY  # Ensure consistent naming

  boot:
    admin:
      client:
        url: http://localhost:8081  # Spring Boot Admin Server
        instance:
          service-base-url: http://localhost:8080  # Fix duplicate registration
          prefer-ip: true  # Register using IP instead of hostname
        metadata:
          instance-id: ${spring.application.name}:${server.port}:${random.value}  # Force unique instance ID

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # Ensure USER-SERVICE is correct in Eureka
          predicates:
            - Path=/users/**

        - id: weCoreAPI
          uri: lb://WECOREAPI  # Ensure WECOREAPI is correct in Eureka
          predicates:
            - Path=/weCoreAPI/**

  main:
    web-application-type: reactive

  security:
    user:
      name: admin
      password: admin  # Fix indentation issue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}  # Force a single unique instance
    prefer-ip-address: false
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}:${random.value}  # Prevent duplicate registration

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
