server:
  port: 8080

spring:
  application:
    name: API-GATEWAY  # Ensure consistent naming

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
            - Path=/users/v3/api-docs 
          filters:
            - RewritePath=/users/v3/api-docs, /v3/api-docs  # Remove prefix before forwarding

        - id: weCoreAPI
          uri: lb://WECOREAPI
          predicates:
            - Path=/weCoreAPI/**, /weCoreAPI/v3/api-docs
          filters:
            - RewritePath=/weCoreAPI/v3/api-docs, /v3/api-docs

  main:
    web-application-type: reactive

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: User Service
        url: /users/v3/api-docs
      - name: WeCore API
        url: /weCoreAPI/v3/api-docs

  api-docs:
    enabled: true
    path: /v3/api-docs
